import type { Metadata } from "next";
import { Geist, Geist_Mono ,Prompt} from "next/font/google";
import "./globals.css";

const geistSans = Prompt({
  variable: "--font-prompt-sans",
  subsets: ["latin"],
  weight: ["700","600","500","400","300"]
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-zinc-950">{children}</body>
    </html>
  );
}
